/**
 * Liste des spécialités médicales (FR) pour l'autocomplete à l'inscription
 * médecin. Couvre les 44 spécialités officielles + sous-spécialités et
 * compétences courantes. La saisie libre reste possible si absent de la liste.
 */
export const SPECIALIZATIONS: string[] = [
  'Addictologie',
  'Allergologie',
  'Anatomie et cytologie pathologiques',
  'Andrologie',
  'Anesthésie-réanimation',
  'Angiologie (médecine vasculaire)',
  'Biologie médicale',
  'Cardiologie',
  'Cardiologie pédiatrique',
  'Chirurgie cardiaque',
  'Chirurgie de la main',
  'Chirurgie esthétique et plastique',
  'Chirurgie maxillo-faciale et stomatologie',
  'Chirurgie orthopédique et traumatologie',
  'Chirurgie pédiatrique',
  'Chirurgie thoracique',
  'Chirurgie vasculaire',
  'Chirurgie viscérale et digestive',
  'Dermatologie et vénéréologie',
  'Diabétologie',
  'Endocrinologie-nutrition',
  'Gastro-entérologie et hépatologie',
  'Génétique médicale',
  'Gériatrie',
  'Gynécologie médicale',
  'Gynécologie-obstétrique',
  'Hématologie',
  'Hépatologie',
  'Immunologie clinique',
  'Maladies infectieuses et tropicales',
  "Médecine d'urgence",
  'Médecine du sport',
  'Médecine du travail',
  'Médecine esthétique',
  'Médecine générale',
  'Médecine interne',
  'Médecine légale et expertises',
  'Médecine nucléaire',
  'Médecine physique et de réadaptation',
  'Médecine tropicale',
  'Néonatologie',
  'Néphrologie',
  'Neurochirurgie',
  'Neurologie',
  'Nutrition',
  'Oncologie médicale',
  'Oncologie-radiothérapie',
  'Ophtalmologie',
  'Oto-rhino-laryngologie (ORL)',
  'Pédiatrie',
  'Phlébologie',
  'Pneumologie',
  'Proctologie',
  'Psychiatrie',
  "Psychiatrie de l'enfant et de l'adolescent",
  'Radiologie et imagerie médicale',
  'Rhumatologie',
  'Santé publique',
  'Sénologie',
  'Sexologie',
  'Soins palliatifs',
  'Toxicologie',
  'Urologie',
];
